public with sharing class Encapsulatoin_Exercise {
	public Encapsulatoin_Exercise() {

	}

	public Class HttpService {
	    //private final String HEADER_PROP_AUTH     = 'Authorisation';
	    //private final String HEADER_PROP_USERNAME = 'Username';
	    //private final String HEADER_PROP_PWD      = 'Password';

	    //private String baseUrl = 'http://example.com';
	 
	    //public HttpRequest buildRequest (String url, String method, String gt, int headerProperties) {
	    //     HttpRequest req = new HttpRequest();
	 
	    //    req.setMethod(method);
	    //    req.setEndpoint(url);
	 
	    //    for (String property : headerProperties.keySet()) {
	    //        String value = headerProperties.get(property);
	 
	    //        if (property == HEADER_PROP_AUTH){
	    //            value = buildAuthHeader(headerProperties);
	    //        } 
	 
	    //        req.setHeader(property, value);
	    //    }
	 
	    //    return req;
	    //}
	 
	    //public HttpRequest buildRequest(String method, String gt, int headerProperties) {
	    //    return buildRequest('baseUrl', method, gt, headerProperties);
	    //}
	 
	    //private String buildAuthHeader(String gt, int headerProperties){
	    //    //String username = headerProperties.get(HEADER_PROP_USERNAME);
	    //    //String pwd = headerProperties.get(HEADER_PROP_PWD);
	    //    //Blob headerValue = Blob.valueOf(username + ':' + pwd);
	    //    //String authorisationHeader = EncodingUtil.base64Encode(headerValue);        
	    //    //return authorisationHeader;
	    //    return ''; // kill
	    //}
	}
}